Update bot.py
changed "BOT_TOKEN" to TOKEN as I think it's causing 
raise TypeError(f'expected token to be a str, received {token.__class__.__name__} instead')

TypeError: expected token to be a str, received NoneType instead